import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import Header from '@/components/share/Header'
import Footer from '@/components/share/Footer'
import ThemeProvider from '@/components/Theme/ThemeProvider'


const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500', '700', '900'], style: ["italic", 'normal'], variable: "--font-poppins" })

export const metadata: Metadata = {
  title: 'HRF | Hotel ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ThemeProvider  >
          <main className='font-normal px-4  '>
            <Header />
            {children}
            <Footer />
          </main>
        </ThemeProvider>
      </body>
    </html >
  )
}
