import type { Metadata } from 'next'
import { Inter, Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500', '700', '900'], style: ["italic", 'normal'], variable: "--font-poppins" })

export const metadata: Metadata = {
  title: 'HRF | Hotel ',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className='font-normal'>

          {children}

        </main>
      </body>
    </html>
  )
}
